name: Checks

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    types:
      - opened # PR was open
      - synchronize # PR was updated
      - reopened # PR was closed and is now open again
      - ready_for_review # PR was converted from draft to open
      - converted_to_draft # PR was converted from open to draft

concurrency:
  group: checks_${{ github.workflow }}_${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Formatting Check
        run: pnpm format:check

      - name: Typecheck
        if: success() || failure()
        run: pnpm typecheck

      # - name: Lint Styles
      #   if: success() || failure()
      #   run: pnpm lint:styles

      - name: Lint
        if: success() || failure()
        run: pnpm lint

      - name: Pack Libs
        if: success() || failure()
        run: |
          pnpm pack --recursive
