name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Skip actual publish
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  unit_tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      id-token: write # to enable use of OIDC for npm provenance
      attestations: write # necessary to persist the attestation
    needs: [checks, unit_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Bump version, add tag, and publish github release
        env:
          BRANCH: ${{github.ref_name}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm exec multi-semantic-release --dry-run=${{ github.event.inputs.dry_run }}

      - name: Remove node_modules
        run: |
          rm -rf packages/**/node_modules/

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: packages
